<a href="https://colab.research.google.com/github/Keistkmiya/Tugas2-Scikit_learn_Cookbook/blob/main/Tugas2_Chapter8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 8: Text Classification

## Processing Text Data with Bag of Words

Model machine learning tidak dapat memahami teks mentah dalam bentuk string secara langsung, sehingga teks tersebut harus diubah terlebih dahulu ke dalam representasi angka atau vektor. Metode Bag of Words (BoW) adalah teknik dasar pemrosesan bahasa alami (NLP) yang menghitung frekuensi kemunculan setiap kata unik di dalam seluruh dokumen. Metode ini mengabaikan urutan kata dan tata bahasa, serta hanya berfokus pada keberadaan kata tersebut di dalam teks. Scikit-learn menyediakan CountVectorizer di dalam modul feature_extraction.text untuk mengubah sekumpulan teks menjadi matriks frekuensi kata.

In [1]:
from sklearn.feature_extraction.text import CountVectorizer

text_data = ["saya suka belajar", "belajar python itu seru", "saya suka python"]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(text_data)

print(vectorizer.get_feature_names_out())
print(X.toarray())

['belajar' 'itu' 'python' 'saya' 'seru' 'suka']
[[1 0 0 1 0 1]
 [1 1 1 0 1 0]
 [0 0 1 1 0 1]]


## Weighting Words with Term Frequency-Inverse Document Frequency (TF-IDF)

Meskipun Bag of Words bisa menghitung frekuensi kata, metode tersebut memiliki kelemahan karena kata-kata yang sangat sering muncul (seperti kata hubung atau kata depan) akan dianggap paling penting, padahal kata-kata tersebut kurang membawa informasi spesifik. TF-IDF (Term Frequency-Inverse Document Frequency) mengatasi hal ini dengan memberikan bobot yang tinggi pada kata yang sering muncul di sebuah dokumen tertentu, tetapi memberikan penalti (bobot rendah) jika kata tersebut muncul di hampir semua dokumen dalam dataset. Scikit-learn menyediakan TfidfVectorizer di dalam modul feature_extraction.text untuk menghitung bobot nilai ini secara otomatis.

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

text_data = ["saya suka belajar", "belajar python itu seru", "saya suka python"]

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(text_data)

print(vectorizer.get_feature_names_out())
print(X.toarray())

['belajar' 'itu' 'python' 'saya' 'seru' 'suka']
[[0.57735027 0.         0.         0.57735027 0.         0.57735027]
 [0.42804604 0.5628291  0.42804604 0.         0.5628291  0.        ]
 [0.         0.         0.57735027 0.57735027 0.         0.57735027]]


## Classifying Text with Naive Bayes

Setelah teks berhasil diubah menjadi bentuk angka (vektor) menggunakan metode seperti BoW atau TF-IDF, kita bisa menggunakan algoritma klasifikasi untuk menentukan kategori dari teks tersebut. Naive Bayes adalah algoritma supervised learning yang sangat populer dan efektif untuk tugas klasifikasi teks, seperti deteksi spam atau analisis sentimen. Algoritma ini bekerja berdasarkan Teorema Bayes dengan asumsi "naif" bahwa setiap fitur (kata) bersifat independen atau tidak saling memengaruhi satu sama lain. Scikit-learn menyediakan class MultinomialNB di dalam modul naive_bayes yang dirancang khusus untuk menangani data diskret seperti frekuensi kemunculan kata dalam teks.

In [3]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

text_data = ["saya suka belajar", "belajar python itu seru", "saya suka python"]
y = np.array([0, 1, 0])

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(text_data)

model = MultinomialNB()
model.fit(X, y)

X_new = vectorizer.transform(["belajar python"])
print(model.predict(X_new))

[0]
