<a href="https://colab.research.google.com/github/Keistkmiya/Tugas2-Scikit_learn_Cookbook/blob/main/Tugas2_Chapter1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 1: Preprocessing Data

## Scaling a Feature to a Range

Proses scaling bertujuan untuk mengubah nilai dari fitur numerik ke dalam rentang tertentu, biasanya antara 0 dan 1. Hal ini sangat penting karena banyak algoritma machine learning yang performanya sensitif terhadap perbedaan skala antar fitur. Scikit-learn menyediakan MinMaxScaler untuk melakukan tugas ini dengan rumus (x - min) / (max - min).

In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

data = np.array([[-1, 2],
                 [-0.5, 6],
                 [0, 10],
                 [1, 18]])

scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(data)

print(data_scaled)

[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]


## Standardizing Features

Standardisasi atau penggantian skala varians mengubah distribusi data sehingga memiliki nilai rata-rata (mean) sama dengan 0 dan standar deviasi sama dengan 1. Proses ini sangat direkomendasikan untuk algoritma yang mengasumsikan data terdistribusi normal, seperti Support Vector Machines (SVM) atau Linear Regression. Scikit-learn menggunakan StandardScaler untuk menghitung rata-rata dan standar deviasi pada data latih agar bisa diterapkan pada data baru.

In [2]:
import numpy as np
from sklearn.preprocessing import StandardScaler

data = np.array([[-1, 2],
                 [-0.5, 6],
                 [0, 10],
                 [1, 18]])

scaler = StandardScaler()
data_standardized = scaler.fit_transform(data)

print(data_standardized)

[[-1.18321596 -1.18321596]
 [-0.50709255 -0.50709255]
 [ 0.16903085  0.16903085]
 [ 1.52127766  1.52127766]]


## Normalizing Features

Normalisasi menskalakan setiap sampel individu (baris data) agar memiliki norma unit. Berbeda dengan standardisasi yang bekerja per kolom (fitur), normalisasi bekerja per baris. Proses ini sering digunakan pada analisis teks atau clustering, di mana arah atau proporsi antar fitur lebih penting daripada nilai absolutnya. Scikit-learn menyediakan Normalizer dengan pilihan norma L1 atau L2.

In [3]:
import numpy as np
from sklearn.preprocessing import Normalizer

data = np.array([[-1, 2],
                 [-0.5, 6],
                 [0, 10],
                 [1, 18]])

normalizer = Normalizer(norm='l2')
data_normalized = normalizer.fit_transform(data)

print(data_normalized)

[[-0.4472136   0.89442719]
 [-0.08304548  0.99654576]
 [ 0.          1.        ]
 [ 0.05547002  0.99846035]]


## Binarizing Features

Binalisasi adalah proses mengubah data numerik kontinu menjadi nilai biner (0 atau 1) berdasarkan ambang batas (threshold) tertentu. Semua nilai yang berada di bawah atau sama dengan ambang batas akan diubah menjadi 0, sedangkan nilai di atas ambang batas akan diubah menjadi 1. Teknik ini berguna ketika nilai kualitatif keberadaan suatu fitur lebih penting daripada kuantitas spesifiknya. Scikit-learn menyediakan Binarizer untuk melakukan transformasi ini secara efisien.

In [4]:
import numpy as np
from sklearn.preprocessing import Binarizer

data = np.array([[-1, 2],
                 [-0.5, 6],
                 [0, 10],
                 [1, 18]])

binarizer = Binarizer(threshold=0.0)
data_binarized = binarizer.fit_transform(data)

print(data_binarized)

[[0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 1.]]


## Handling Categorical Features

Banyak algoritma machine learning tidak dapat memproses data kategori berupa teks secara langsung dan membutuhkan input numerik. Salah satu teknik untuk menangani data kategori nominal adalah One-Hot Encoding, di mana setiap nilai kategori unik diubah menjadi kolom baru bernilai biner (0 atau 1). Scikit-learn menyediakan OneHotEncoder untuk mengonversi data string atau label kategori menjadi representasi matriks biner yang siap digunakan oleh model.

In [5]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

data = np.array([['Cold'],
                 ['Warm'],
                 ['Hot'],
                 ['Cold']])

encoder = OneHotEncoder(sparse_output=False)
data_encoded = encoder.fit_transform(data)

print(data_encoded)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


## Imputing Missing Values

Dataset di dunia nyata sering kali memiliki nilai yang hilang (missing values) akibat kesalahan input atau kegagalan sistem. Sebelum melatih model, nilai yang kosong ini harus ditangani karena sebagian besar algoritma scikit-learn tidak menerima input data yang mengandung nilai kosong. Salah satu strategi dasar adalah imputasi, yaitu mengisi nilai yang hilang menggunakan nilai statistik seperti rata-rata (mean), median, atau nilai yang paling sering muncul (most frequent) dari kolom tersebut. Scikit-learn menyediakan SimpleImputer untuk mempermudah proses ini.

In [6]:
import numpy as np
from sklearn.impute import SimpleImputer

data = np.array([[1, 2],
                 [np.nan, 6],
                 [7, np.nan],
                 [10, 12]])

imputer = SimpleImputer(strategy='mean')
data_imputed = imputer.fit_transform(data)

print(data_imputed)

[[ 1.          2.        ]
 [ 6.          6.        ]
 [ 7.          6.66666667]
 [10.         12.        ]]


## Generating Polynomial Features

Ketika hubungan antara fitur dan target bersifat non-linear, pembuatan fitur polinomial dapat membantu model linear menangkap pola yang lebih kompleks. Teknik ini bekerja dengan membuat kombinasi perkalian antar fitur yang ada serta memangkatkannya hingga derajat tertentu. Scikit-learn menyediakan PolynomialFeatures yang dapat secara otomatis menghasilkan kolom baru berisi interaksi antar fitur tersebut untuk meningkatkan kapasitas representasi model linear.

In [7]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

data = np.array([[2, 3],
                 [4, 5]])

poly = PolynomialFeatures(degree=2)
data_poly = poly.fit_transform(data)

print(data_poly)

[[ 1.  2.  3.  4.  6.  9.]
 [ 1.  4.  5. 16. 20. 25.]]


## Custom Transformers

Scikit-learn menyediakan berbagai metode transformasi bawaan, namun terkadang kita memerlukan transformasi kustom yang spesifik untuk kebutuhan data tertentu. Dengan menggunakan FunctionTransformer, kita dapat mengubah fungsi Python biasa menjadi sebuah transformer yang kompatibel dengan alur kerja scikit-learn. Hal ini mempermudah integrasi pembersihan data atau manipulasi matematis kustom ke dalam pipeline pemrosesan data.

In [8]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer

data = np.array([[1, 4],
                 [9, 16]])

log_transformer = FunctionTransformer(np.log1p)
data_transformed = log_transformer.transform(data)

print(data_transformed)

[[0.69314718 1.60943791]
 [2.30258509 2.83321334]]
