<a href="https://colab.research.google.com/github/Keistkmiya/Tugas2-Scikit_learn_Cookbook/blob/main/Tugas2_Chapter9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 9: Neural Networks

## Classifying Data with the Perceptron

Perceptron adalah unit fundamental dan bentuk paling sederhana dari sebuah jaringan saraf tiruan (Neural Network). Algoritma ini mensimulasikan cara kerja sel saraf biologis dengan menerima beberapa masukan (input), mengalikannya dengan bobot (weights) masing-masing, menambahkan bias, dan melewatkan hasilnya ke sebuah fungsi aktivasi untuk menghasilkan keluaran biner (0 atau 1). Perceptron termasuk dalam klasifikasi linear, yang berarti algoritma ini hanya dapat memisahkan data yang bersifat linearly separable (dapat dipisahkan dengan garis lurus). Scikit-learn menyediakan class Perceptron di dalam modul linear_model.

In [1]:
import numpy as np
from sklearn.linear_model import Perceptron

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 0, 0, 1])

model = Perceptron(max_iter=100, tol=1e-3, random_state=42)
model.fit(X, y)

print(model.predict(X))
print(model.coef_)

[0 0 0 1]
[[2. 2.]]


## Classifying Data with the Multi-layer Perceptron (MLP)

Ketika data yang dihadapi memiliki pola yang kompleks dan tidak bisa dipisahkan secara linear, model Perceptron tunggal tidak akan mampu menyelesaikannya. Multi-layer Perceptron (MLP) mengatasi masalah ini dengan menggabungkan banyak neuron ke dalam beberapa lapisan struktur jaringan saraf tiruan, yang terdiri dari Input Layer, Hidden Layer (lapisan tersembunyi), dan Output Layer. MLP menggunakan algoritma Backpropagation untuk memperbarui bobot berdasarkan nilai error (kesalahan) yang dihasilkan selama proses pelatihan. Dengan adanya lapisan tersembunyi dan fungsi aktivasi non-linear, MLP mampu mempelajari pola data yang sangat rumit. Scikit-learn menyediakan MLPClassifier di dalam modul neural_network.

In [2]:
import numpy as np
from sklearn.neural_network import MLPClassifier

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 1, 1, 0])

model = MLPClassifier(hidden_layer_sizes=(4,), max_iter=2000, random_state=42)
model.fit(X, y)

print(model.predict(X))

[0 0 0 0]
