<a href="https://colab.research.google.com/github/Keistkmiya/Tugas2-Scikit_learn_Cookbook/blob/main/Tugas2_Chapter7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 7: Clustering

## Grouping Data with K-Means

K-Means adalah algoritma pembelajaran tanpa pengawasan yang paling populer untuk mengelompokkan data ke dalam sejumlah k kluster. Algoritma ini bekerja secara iteratif dengan menentukan k titik pusat kluster awal (centroid), memasukkan setiap titik data ke centroid terdekat berdasarkan jarak Euclidean, lalu memperbarui posisi centroid berdasarkan rata-rata posisi data di dalam kluster tersebut. Proses ini diulang hingga posisi centroid tidak lagi berubah secara signifikan. Scikit-learn menyediakan KMeans di dalam modul cluster untuk melakukan pengelompokkan data ini.

In [1]:
import numpy as np
from sklearn.cluster import KMeans

X = np.array([[1, 2], [1, 4], [1, 0], [10, 2], [10, 4], [10, 0]])

model = KMeans(n_clusters=2, random_state=42, n_init='auto')
model.fit(X)

print(model.labels_)
print(model.cluster_centers_)

[0 0 0 1 1 1]
[[ 1.  2.]
 [10.  2.]]


## Grouping Data with Affinity Propagation

Affinity Propagation adalah algoritma klusterisasi yang tidak mengharuskan kita untuk menentukan jumlah kluster (k) di awal proses. Algoritma ini bekerja dengan cara mengirimkan pesan atau nilai kecocokan antar titik data secara iteratif untuk menentukan titik mana yang paling layak mewakili titik lainnya, yang disebut sebagai exemplar. Kluster terbentuk secara organik berdasarkan bagaimana pesan-pesan tersebut mencapai titik keseimbangan. Pendekatan ini sangat efektif untuk menemukan kluster yang memiliki ukuran atau bentuk yang tidak seragam. Scikit-learn menyediakan AffinityPropagation di dalam modul cluster.

In [2]:
import numpy as np
from sklearn.cluster import AffinityPropagation

X = np.array([[1, 2], [1, 3], [2, 2], [8, 9], [8, 8], [9, 8]])

model = AffinityPropagation(random_state=42)
model.fit(X)

print(model.labels_)
print(model.cluster_centers_indices_)

[0 0 0 1 1 1]
[0 4]
